config/routes.rb
Furia::Engine.routes.draw do
  resources :samples, only: %i[index show destroy]
  root to: redirect("samples")
end

app/models/furia/sample.rb
# frozen_string_literal: true

module Furia
  class Sample < ActiveRecord::Base
    serialize :data, JSON

    def root_group
      @root_group ||= Furia.entry_from_hash(data)
    end
  end
end

app/controllers/furia/application_controller.rb
module Furia
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    layout "furia/application"
  end
end

app/controllers/furia/samples_controller.rb
# frozen_string_literal: true

module Furia
  class SamplesController < ApplicationController
    before_action :set_sample, only: %i[show destroy]

    def index
      @samples = Sample.order(created_at: :desc)
    end

    def show
    end

    def destroy
      @sample.destroy
      redirect_to samples_path
    end

    private

    def set_sample
      @sample = Sample.find(params[:id])
    end
  end
end

app/helpers/furia/application_helper.rb
module Furia
  module ApplicationHelper
  end
end

app/views/furia/samples/_entry.html.erb
<% if entry.is_a?(Furia::Query) %>
  <div class="accordion accordion-single font-monospace">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#query-<%= entry.uid %>">
          <small>
            [<span class="text-success"><%= entry.duration_ms.floor(2) %>ms</span>]
            <% if entry.cached %>
              [<span class="text-secondary">CACHED</span>]
            <% end %>
            <span>
              <code class="language-sql bg-transparent"><%= entry.sql %></code>
            </span>
          </small>
        </button>
      </h2>

      <div id="query-<%= entry.uid %>" class="accordion-collapse collapse">
        <div class="accordion-body">
          <small>
            Stacktrace:
            <ul>
              <% entry.stacktrace.each do |line| %>
                <li><%= line %></li>
              <% end %>
            </ul>
          </small>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% if entry.is_a?(Furia::Group) %>
  <%= render "group", group: entry %>
<% end %>

app/views/furia/samples/_group.html.erb
<div class="entries">
  <button class="scope-label" data-bs-toggle="collapse" data-bs-target="#scope-<%= group.uid %>">
    <%= group.scope %> [<%= group.total_duration_ms.floor(2) %>ms]
  </button>

  <div class="collapse show" id="scope-<%= group.uid %>">
    <% group.entries.each do |entry| %>
      <%= render "entry", entry: entry %>
    <% end %>
  </div>
</div>

app/views/furia/samples/index.html.erb
<h2 class="my-4">All Samples</h2>

<% if @samples.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Scope</th>
        <th>Total Duration</th>
        <th>Queries number</th>
        <th>Created</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @samples.each do |sample| %>
        <tr>
          <td><%= sample.id %></td>
          <td><%= sample.root_group.scope %></td>
          <td><%= sample.root_group.total_duration_ms.floor(2) %>ms</td>
          <td><%= sample.root_group.total_queries_num %></td>
          <td><%= l sample.created_at, format: :short %></td>
          <td>
            <%= link_to "View", sample_path(sample) %>
            &nbsp;
            <%= link_to "Destroy", sample_path(sample), class: "text-danger", data: { confirm: "Are you sure you want to destroy this sample?", method: "DELETE" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="card">
    <div class="card-body text-center">
      Nothing yet ¯\_(ツ)_/¯
    </div>
  </div>
<% end %>

app/views/furia/samples/show.html.erb
<h2 class="my-4">Sample #<%= @sample.id %> from <%= l @sample.created_at, format: :short %></h2>

<%= render "group", group: @sample.root_group %>

app/views/layouts/furia/application.html.erb
<!doctype html>
<html>
  <head>
    <title>Furia</title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "furia/application" %>
    <%= javascript_include_tag "furia/application" %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/prismjs@1.30.0/themes/prism.min.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Furia</a>

        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="<%= samples_path %>">Samples</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container-fluid">
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/prismjs@1.30.0/components/prism-core.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/prismjs@1.30.0/plugins/autoloader/prism-autoloader.min.js"></script>
  </body>
</html>